version: '3'
services:
  proshopclient:
    image: proshopclient
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - pern-app
  proshopserver:
    image: proshopserver
    ports:
      - '5000:5000'
    networks:
      - pern-app
networks:
  pern-app:
    driver: bridge
